### PR TITLE
Enabling multiple Unicodes

### LINKED ISSUE #62: Multiple Unicodes
Hi @typemytype, 

I might be doing something wrong — but I'm making an all-caps font, and I want to make sure that my glyphs built with GlyphConstruction have two unicodes (one for upper and one for the lowercase). For instance:

I want to build Agrave (U+00C0), but I also want it to have the unicode for the lowercase agrave (U+00E0). I put in
```
Agrave = A + grave @ top | 0x00C0, 0x00E0
```
but it only gets the first unicode. I looked in the source and indeed it only seems possible to set one unicode (unless I am mistaken). 

If I am doing something wrong, please let me know! But if not, do you think we should consider adding the ability to set more than one unicode value?

Thanks!

### PR DESCRIPTION
**Pull request by colinmford**
Allows multiple unicodes to be set in a glyph construction equation.

Note that this may be a breaking change for some scripts (outside of Glyph Builder), since previously the "unicode" value returned an `int`, now it returns a `tuple` no matter what. If this is undesirable we can find a work around I suppose, but I believe the impact will be minimal.

For examples, see doctest changes in `Lib/glyphConstruction.py`

Fixes #62.

### CODE REVIEW

**Comment by typemytype** [comment]
looks good, will test over the weekend

small comment: for legacy reasons it would be good to add a `constructionGlyph.unicodes ` attribute returning the first value of the `constructionGlyph.unicodes`, only a getter is fine, no setter. This is also the behaviour in defcon, fontParts... 

```python
def _get_unicode(self):
     if self.unicodes:
          return self.unicodes[0] 
     return None

unicode = property(_get_unicode)
```

**Comment by colinmford** [comment]
@typemytype Easy enough, added!

**Comment by typemytype** [comment]
super thanks!!

**Comment by colinmford** [comment]
Thanks, @typemytype !

**Pull request merged**
